---

# - name: "PRELIM | Detect if Trusted Platform Module (TPM) is available"
#   win_shell: (Get-CimInstance -ClassName Win32_OperatingSystem).ProductType
#   register: win10stig_tpm_enabled
#   changed_when: no
#   failed_when: no
#   tags:
#       - always

# - name: "PRELIM | Detect if Remote Desktop Services (RDP) is enabled"
#   win_reg_stat:
#       path: HKLM:\System\CurrentControlSet\Control\Terminal Server
#       name: fDenyTSConnections
#   register: win10stig_rdp_enabled
#   changed_when: no
#   failed_when: no
#   tags:
#       - always

- name: "PRELIM | Get Display Version value."
  win_reg_stat:
      path: HKLM:\Software\Microsoft\Windows NT\CurrentVersion
      name: DisplayVersion
  changed_when: false
  failed_when: false
  register: win10_displayversion

- name: "PRELIM | Get OS Build value."
  win_reg_stat:
      path: HKLM:\Software\Microsoft\Windows NT\CurrentVersion
      name: CurrentBuild
  changed_when: false
  failed_when: false
  register: win10_currentbuild


- name: "PRELIM | Get Admin Users and Groups"
  win_shell: Get-LocalGroupMember -Name 'Administrators'
  changed_when: false
  failed_when: false
  register: wn10stig_admin_users_groups
  when:
      - wn10_00_000070 or
        wn10_00_000240
