---

# Use of this flag is not recommended per Microsoft's documentation. https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-gpsb/0b40db09-d95d-40a6-8467-32aedec8140c
- name: "HIGH | WN10-AC-000045 | PATCH | Reversible password encryption must be disabled."
  when:
    - wn10_ac_000045 | bool
    - not discovered_account_policy_is_domain_scoped | bool
  tags:
    - WN10-AC-000045
    - CAT1
    - CCI-000196
    - CCI-004062
    - SRG-OS-000073-GPOS-00041
    - SV-220747r1051024_rule
    - V-220747
    - NIST800-53_IA-5_1_c
    - NIST800-53A_IA-5_1.1_v
    - NIST800-53R4_IA-5_1_c
  community.windows.win_security_policy:
    section: System Access
    key: ClearTextPassword
    value: "0"
