---

- name: "LOW | WN10-UC-000015 | PATCH | Toast notifications to the lock screen must be turned off."
  when: wn10_uc_000015 | bool
  tags:
    - WN10-UC-000015
    - CAT3
    - CCI-000381
    - SRG-OS-000095-GPOS-00049
    - SV-220954r958478_rule
    - V-220954
    - NIST800-53_CM-7
    - NIST800-53A_CM-7.1_ii
    - NIST800-53R4_CM-7_a
  ansible.windows.win_regedit:
    path: HKCU:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\PushNotifications
    name: NoToastApplicationNotificationOnLockScreen
    data: 1
    type: dword
