prefix         = "lockdown_github_repo_workflow"
location       = "eastus"
tagname        = "ansible_lockdown"
system_size    = "Standard_DC4s_v2"
OS_publisher   = "MicrosoftWindows"
OS_version     = "2010"
system_release = "Datacenter-g2"
hostname       = "github"
